# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.25.095508'

RELEASE_GIT_HEAD = '89f535e2656964b4061c25a7739d4d6ba0a30568'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'qifeikeji/yt-dlp'

ORIGIN = 'qifeikeji/yt-dlp'

_pkg_version = '2024.04.25.095508'
